name: PIP upload - tgwrapper

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
        
      - name: Build & Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PIP_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*

